### ISSUE TITLE
Number and Int instances

### ISSUE THREAD

**Issue by dwhitney** [athanclark/purescript-arraybuffer-class#1]
I'm curious why you've left out type class instances for `Number` and `Int`. If you have no objection, I'd happily write them for you.

**Comment by athanclark** [comment]
Just because it's ambiguous - I'm not sure if everyone realizes that an Int would take up 4 bytes, and a Number would take 8 - it's also to prevent accidental usage of the values without strict control over the byte size used. However, I'm not exactly opposed to an instance - feel free to add one!

**Comment by dwhitney** [comment]
I will probably hold off for now. I tried this library yesterday and it works well for small things, but I had a 1.5 megabyte record I wanted to serialized and it took many minutes to do so. I wrote some code to serialize many of its fields to ArrayBuffers with JS, but I could not get the full thing to serialize in anything much less than a full second. When I serialize it with JS it takes about 35ms. This is a particularly performance critical part of my codebase, so I think I'll have to stick with JS for now.
